### ISSUE TITLE
Conflicting function getline() of xa and stdio

### ISSUE THREAD

**Issue by m-butti** [fachat/xa65#1]
If I try to compile right away on Mac OS 10.8.4 I get this error:

xa.c:95: error: conflicting types for ‘getline’
/usr/include/stdio.h:449: error: previous declaration of ‘getline’ was here

The solution is pretty simple. Just renamed the getline() function in xa so it doesn't conflict with the same named function of stdio.

Thank you very much.
I really like this piece of software :-)

**Comment by fachat** [comment]
fixed in 2.3.9
