### ISSUE TITLE
GeckOsV2 does not build with V2.3.13

### ISSUE THREAD

**Issue by eibach** [fachat/xa65#11]
Building GeckOsV2 with v2.3.13 fails with lots of errors. It works fine with v2.3.12.
Here is the beginning of the build output:
(cd apps; make;)
make[1]: Entering directory '/mnt/c/Users/EibachD/src/GeckOS-V2/apps'
(for i in * ; do\
(if test -d $i; then cd $i; make; fi;); \
done)
make[2]: Entering directory '/mnt/c/Users/EibachD/src/GeckOS-V2/apps/file'
xa -I../../include -R -LLIB6502 mkdir.a65 -o mkdir
/****************************************************************************
inet.i65:line 2: 1000:Syntax error
    OS/A65 Version 1.4.0
inet.i65:line 4: 1000:Syntax error
    Multitasking Operating System for 6502 Computers
inet.i65:line 5: 1000:Syntax error
    Copyright (C) 1989-1997 Andre Fachat
inet.i65:line 7: 1000:Syntax error
    it under the terms of the GNU General Public License as published by
inet.i65:line 10: 1000:Label already defined error
    the Free Software Foundation; either version 2 of the License, or
inet.i65:line 11: 1000:Label already defined error
    (at your option) any later version.
inet.i65:line 12: 1000:Syntax error
    This program is distributed in the hope that it will be useful,
inet.i65:line 14: 1000:Label already defined error
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the

**Comment by fachat** [comment]
GeckOS works fine with xa 2.4.1
