### ISSUE TITLE
Immediate mode 65816, 16-bit value generates overflow error

### ISSUE THREAD

**Issue by anoxic83** [fachat/xa65#12]
xa -w test.asm
ldx #$5654
test.asm:line 6: 0006:Overflow error
Break after 1 errors

documentation of WDC65C816 (https://www.westerndesigncenter.com/wdc/documentation/w65c816s.pdf):
3.5.18 Immediate-#
With Immediate (#) addressing the operand is the second byte (second and third bytes when in the
16-bit mode) of the instruction.

**Comment by classilla** [comment]
(See this and other related pseudo-ops: http://www.floodgap.com/retrotech/xa/xa.1.html )
